# Generated by Django 2.2.1 on 2019-05-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_customers_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='customers',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
