# Generated by Django 2.2.1 on 2019-05-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190502_0409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Tailors',
            new_name='Tailor',
        ),
    ]
