# Generated by Django 2.2.1 on 2019-05-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190502_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60)),
                ('order_number', models.IntegerField(default=0)),
                ('item', models.CharField(choices=[('1', 'Dress 1'), ('2', ''), ('3', 'Singapore')], default='', max_length=1)),
                ('color', models.CharField(choices=[('B', 'Black'), ('G', 'Gray'), ('B', 'Navy Blue'), ('R', 'Red')], default='', max_length=1)),
                ('order_time', models.IntegerField(default=0)),
            ],
        ),
    ]
