# Generated by Django 2.2.1 on 2019-05-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(choices=[('1', 'Dress 1'), ('2', 'Dress 2'), ('3', 'Dress 3')], default='', max_length=1),
        ),
    ]
