# Generated by Django 2.2.1 on 2019-05-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20190502_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fabric',
            field=models.CharField(choices=[('P', 'Polyester'), ('C', 'Cotton'), ('R', 'Raeyon')], default='', max_length=1),
        ),
    ]
